version: '3'

services:

  commonui-sample:
    build:
      context: .
    image: vertigoala/commonui-sample:latest
    volumes:
      - ./html:/opt/html
    ports:
      - 8000:80
    command: ["sh","-c","nginx; while true; do echo 'sync...'; cp -R /opt/html /usr/share/nginx/; sleep 2; done"]
      
